export const apiRoutes = {
  register: "/api/v1/auth/register",
  login: "/api/v1/auth/login",
  googleLogin: "/api/v1/auth/google",
  forgotPassword: "/api/v1/auth/forgot-password",
  verifyOTP: "/api/v1/auth/verify-otp",
  resetPassword: "/api/v1/auth/reset-password",
  refresh: "/api/v1/auth/refresh",
  me: "/api/v1/auth/me",
  workspace: "/api/v1/workspace",
  convert: "/api/v1/convert",
  runWorkspace: "/run-workspace",
  runParser: "/api/v1/run-parser",
  history: "/api/v1/history",
  deleteHistory: (id: string) => `/api/v1/history/${id}`,
  deleteConversionSnippet: (collectionId: string, snippetId: string) => `/api/v1/conversions/snippet/${encodeURIComponent(collectionId)}/${encodeURIComponent(snippetId)}`,
  deleteConversionCollection: (collectionId: string) => `/api/v1/conversions/collection/${encodeURIComponent(collectionId)}`,
  renameConversionCollection: (collectionId: string) => `/api/v1/conversions/collection/${encodeURIComponent(collectionId)}/name`,
  createIssue: "/api/v1/issues",
  createIssueFallback: "/issues",
  listIssues: "/api/v1/issues",
  listIssuesFallback: "/issues",
  getIssue: (issueId: string) => `/api/v1/issues/${encodeURIComponent(issueId)}`,
  getIssueFallback: (issueId: string) => `/issues/${encodeURIComponent(issueId)}`,
  issueFile: (issueId: string, fileIndex: number) => `/api/v1/issues/${encodeURIComponent(issueId)}/files/${fileIndex}`,
  issueFileFallback: (issueId: string, fileIndex: number) => `/issues/${encodeURIComponent(issueId)}/files/${fileIndex}`,
  listIssuesAdmin: "/api/v1/issues/admin",
  listIssuesAdminFallback: "/issues/admin",
  resolveIssue: (issueId: string) => `/api/v1/issues/admin/${encodeURIComponent(issueId)}/resolve`,
  resolveIssueFallback: (issueId: string) => `/issues/admin/${encodeURIComponent(issueId)}/resolve`,
  updateIssueStatus: (issueId: string) => `/api/v1/issues/admin/${encodeURIComponent(issueId)}/status`,
  updateIssueStatusFallback: (issueId: string) => `/issues/admin/${encodeURIComponent(issueId)}/status`,
  deleteIssue: (issueId: string) => `/api/v1/issues/admin/${encodeURIComponent(issueId)}`,
  deleteIssueFallback: (issueId: string) => `/issues/admin/${encodeURIComponent(issueId)}`,
  health: "/health",
} as const;
